# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7af045abaae32f9696876d54b8b9264306417047d7fccde03901cc9f85b6317ed7b2e630d7e1f6ba9af4d058c2cdfcbd707190de54c73e4bbdc68cf56744b6

test:
  secret_key_base: 7e3a79adc2ebf674301f41bb8cf8377292e84f79d37c12d6d7cc297496a348a83465b06e046f20869104868f6d912321331caf0a14a537e662f9bcd01b8fdcb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
